### ISSUE TITLE
new background image for bootloader

### ISSUE THREAD

**Issue by machinebacon** [linuxbbq/anorexia2016_issues#10]

**Comment by wuxmedia** [comment]
you can use any of my walls bacon, or a new commision perhaps?
maybe this one:
http://linuxbbq.org/wallpapers/wux19.jpg
I take it this is just for the live image? 
Not carried onto the grub menu

**Comment by machinebacon** [comment]
correct, just for the syslinux menu. I would prefer something "branded" and simplistic, but of course thanks for the offer ;)

**Comment by machinebacon** [comment]
I should mention, that this image is also the backdrop for fbterm sessions, so something dark, low contrast would be optimal.

**Comment by wuxmedia** [comment]
Ahh nice..
http://linuxbbq.org/wallpapers/wall1366x768.png
tweaked to be darker :
http://linuxbbq.org/wallpapers/bbq-dark.png

**Comment by machinebacon** [comment]
^ that would be the best, thanks. I check how it looks like with different resolutions, hope it gets centred, not stretched ;)

**Comment by wuxmedia** [comment]
Let me know if need it GIMPing up for various screen resolutions.
I suppose best way with the terminal would be to program the transparent 'bbqtux' png in the centre over a background colour.
there was a thread somewhere using hsetroot for that i think

**Comment by machinebacon** [comment]
In the past it was like this, yes, simply hsetroot'ing with the tux in the center. Actually the little tux alone, centred, on a transparent background will do. I'll play around with it for the 3rd alpha and see how it looks. 2nd alpha is on the grill right now.

**Comment by machinebacon** [comment]
no bootloader background for now. black is beautiful. 
/closed
