### ISSUE TITLE
add items to slmenu

### ISSUE THREAD

**Issue by machinebacon** [linuxbbq/anorexia2016_issues#24]
env-info, dkeger, scrot, htop, bc, poweroff, reboot, pm-suspend, and others

**Comment by wuxmedia** [comment]
some of those IIRC are not on the base install htop isn't, nor scrot.

**Comment by machinebacon** [comment]
should have been "top", not htop, right. scrot is bullshit, should be fbcat/fbgrab.

**Comment by machinebacon** [comment]
added alsamixer, top, env-info, pm-suspend, reboot, poweroff, and others. if user wants, more items can be added manually
/closed
